services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60

  express_app:
    image: remioluwatomi/express-app:latest
    ports:
      - "3000:8080"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    container_name: express_app